fruits = {"apple": 50, "banana": 100}
print(fruits)
print(fruits.get("apple"))
print(fruits['apple'])
print(fruits.get("berry"))
print(fruits.get("berry", 70))
print(fruits.get("apple", 70))
print(fruits)
fruit = fruits.pop('apple')
print(fruit, fruits)
fruit = fruits.setdefault('banana', 70)
print(fruit, fruits)
fruit = fruits.setdefault('berry', 70)
print(fruit, fruits)